title:       Codewars Documentation
description: Documentation for Codewars

# This might be useful when reusing the documentation for Qualified.
# Replace 'Codewars' in the documentation with '{{ site.platform }}'
# and override the value with additional config file when building.
# It should be possible to extend this to support words/paragraph switching by
# using data files in conjunction with this variable.
# '{{ site.data.switches[site.platform].foo }}' for contents depending on CW/Q
# To make this work with front matters,
# a workaround using a placeholder is necessary.
# '{{ page.title | replace: "%PLATFORM%", site.platform }}'
# platform: Codewars

url: ""
baseurl: "/docs.codewars.com"

collections:
  infos:
    output: true
    permalink: /about/:path/
  languages:
    output: true
    permalink: /languages/:path/
  test_references:
    output: true
    permalink: /languages/:path/
  references:
    output: true
    permalink: /references/:path/
  tutorials:
    output: true
    permalink: /tutorials/:path/
  recipes:
    output: true
    permalink: /cookbook/:path/
  json:
    output: true
    permalink: /json/:path

defaults:
  - scope:
      path: ""
      type: "infos"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "languages"
    values:
      layout: "language"
  - scope:
      path: ""
      type: "test_references"
    values:
      layout: "test_reference"
  - scope:
      path: ""
      type: "references"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "tutorials"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "recipes"
    values:
      layout: "recipe"
  - scope:
      path: ""
      type: "json"
    values:
      layout: "none"

# Build settings
highlighter: rouge
# highlighter: none
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
  # syntax_highlighter_opts: {disable: true}
  entity_output:  as_char
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  toc_levels:     1..6
  footnote_nr:    1

sass:
  sass_dir: _scss
  style: compressed

include: ["_pages"]

# Disabling @mention support because it's causing issues with code.
# gems:
#   - jekyll-mentions
#
# jekyll-mentions:
#   base_url: https://www.codewars.com/users

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - '*/README.md'
  - 'assets/css/fonts/*.json'
